# Generated by Django 5.2.7 on 2025-10-30 12:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "description_short",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "description_long",
                    ckeditor.fields.RichTextField(verbose_name="Полное описание"),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="places/", verbose_name="Изображение"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.place",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение места",
                "verbose_name_plural": "Изображения мест",
                "ordering": ["position", "id"],
            },
        ),
    ]
