# Generated by Django 5.2.7 on 2025-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7, max_digits=9, verbose_name="Долгота"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=200, unique=True, verbose_name="Название"),
        ),
    ]
