# Generated by Django 5.2.7 on 2025-10-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_place_latitude_alter_place_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Долгота"
            ),
        ),
    ]
