services:

  db:
    image: mysql
    env_file:
      - ./configs/db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      interval: 30s
    networks:
      - backend-network


  django:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    command: >
      sh -c "
      python3 src/manage.py makemigrations && 
      python3 src/manage.py migrate && 
      python3 src/manage.py collectstatic --noinput &&
      find /code/src/places -type f -exec python3 src/manage.py load_place {} \; &&
      gunicorn --bind 0.0.0.0:8000 core.wsgi:application --chdir src"
    volumes:
      - ./src:/code/src
    env_file:
      - ./configs/django.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
    

  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - ./src/staticfields:/static
      - ./src/media:/media
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      db:
        condition: service_healthy
      django:
        condition: service_started
    networks:
      - backend-network
  


networks:
  backend-network:
    driver: bridge